# version: 1.0.0

add_newline = false
palette = "catppuccin_mocha"
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($nix_shell$container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
$battery\
$time"""

[fill]
symbol = ''

[character]
format = "$symbol "
success_symbol = "[◎](bold italic bright-yellow)"
error_symbol = "[○](italic purple)"
vimcmd_symbol = "[■](italic dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = false


[cmd_duration]
format = "[◄ $duration ](italic white)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[▶](blue italic)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](italic bold green)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic bright-blue"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[◪◦](italic bright-magenta)"
ahead = "[▴│[${count}](bold white)│](italic green)"
behind = "[▿│[${count}](bold white)│](italic red)"
diverged = "[◇ ▴┤[${ahead_count}](regular white)│▿┤[${behind_count}](regular white)│](italic bright-magenta)"
untracked = "[◌◦](italic bright-yellow)"
stashed = "[◃◈](italic white)"
modified = "[●◦](italic yellow)"
staged = "[▪┤[$count](bold white)│](italic bright-cyan)"
renamed = "[◎◦](italic bright-blue)"
deleted = "[✕](italic red)"

[deno]
format = " [deno](italic) [∫ $version](green bold)"
version_format = "${raw}"

[lua]
symbol = " "
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
style = "bold bright-yellow"

[nodejs]
symbol = " "
format = " [node](italic) [◫ ($version)](bold bright-green)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
symbol = " "
format = " [py](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
style = "bold bright-yellow"

[ruby]
symbol = " "
format = " [rb](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
style = "bold red"

[rust]
symbol = "󱘗 "
format = " [rs](italic) [$symbol$version]($style)"
version_format = "${raw}"
style = "bold red"

[package]
symbol = "󰏗 "
format = " [pkg](italic dimmed) [$symbol$version]($style)"
version_format = "${raw}"
style = "dimmed yellow italic bold"

[swift]
symbol = " "
format = " [sw](italic) [${symbol}${version}]($style)"
style = "bold bright-red"
version_format = "${raw}"

[aws]
symbol = "  "
disabled = true
format = " [aws](italic) [$symbol $profile $region]($style)"
style = "bold blue"

[buf]
symbol = " "
format = " [buf](italic) [$symbol $version $buf_version]($style)"

[c]
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[conda]
symbol = " "
format = " conda [$symbol$environment]($style)"

[dart]
symbol = " "
format = " dart [$symbol($version )]($style)"

[docker_context]
symbol = " "
format = " docker [$symbol$context]($style)"

[elixir]
symbol = " "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[elm]
symbol = " "
format = " elm [$symbol($version )]($style)"

[golang]
symbol = " "
format = " go [$symbol($version )]($style)"

[haskell]
symbol = " "
format = " hs [$symbol($version )]($style)"

[java]
symbol = " "
format = " java [${symbol}(${version} )]($style)"

[julia]
symbol = " "
format = " jl [$symbol($version )]($style)"

[memory_usage]
symbol = "󰍛 "
format = " mem [${ram}( ${swap})]($style)"

[nim]
symbol = "󰆥 "
format = " nim [$symbol($version )]($style)"

[nix_shell]
symbol = " "
style = 'bold italic dimmed blue'
format = '[$symbol nix⎪$state⎪]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed ellow)'

[spack]
format = " spack [$symbol$environment]($style)"





[crystal]
symbol = " "


[directory]
read_only = " 󰌾"




[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "


[guix_shell]
symbol = " "


[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "



[kotlin]
symbol = " "



[meson]
symbol = "󰔷 "




[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "


[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "


[rlang]
symbol = "󰟔 "



[scala]
symbol = " "


[zig]
symbol = " "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
